### ISSUE TITLE
updateObjectWithKeyAndValue issue

### ISSUE THREAD

**Issue by latinadeveloper** [learn-co-curriculum/javascript-objects#11]
Same answer for destructivelyUpdateObjectWithKeyAndValue works with updateObjectWithKeyAndValue

Both of these pass the test.

```
function updateObjectWithKeyAndValue(object, key, value){
  return Object.assign ({}, object, {[key] : value})
}
```

```
function updateObjectWithKeyAndValue(object, key, value){
  object[key]=value
  return object
}
```

**Comment by bhollan** [comment]
CC: @aturkewi @Lukeghenco

**Comment by aturkewi** [comment]
@isisharris @bhollan I'm a bit confused here. It looks like these are the only tests for this lab: https://github.com/learn-co-curriculum/javascript-objects/blob/master/test/objects-test.js

I'm not see any tests for `destructivelyUpdateObjectWithKeyAndValue` or for `updateObjectWithKeyAndValue`. Can either of you explain where you are seeing these tests? Or is this issue no longer relevant?

**Comment by gj** [comment]
@aturkewi different lab: https://github.com/learn-co-curriculum/javascript-objects-lab

**Comment by aturkewi** [comment]
Closing. Tracking this issue on the appropriate lab: https://github.com/learn-co-curriculum/javascript-objects-lab/issues/7
