### ISSUE TITLE
Purpose of {} in Object assign

### ISSUE THREAD

**Issue by mike7352** [learn-co-curriculum/javascript-objects#18]
What is the difference between:

Object.assign ( object, { [key] : value })

and

Object.assign ( {}, object, { [key] : value })

**Comment by JessRudder** [comment]
Hi @mike7352 in the first one, all of the key/value pairs from the other objects will be merged onto `object` which will cause it to change from what it was previously.

In the second one, you are merging all of the key/value pairs onto a blank object.  This allows that original `object` to be unchanged.

Although there are many reasons to use the 2nd, for our purposes, it's most important when you get to React/Redux as the state is kept in an object and you are not supposed to mutate state in React.

With future questions, I suggest using the "Ask a Question" feature on the right hand side of Learn so a Learn Expert can help you in real time.
