### ISSUE TITLE
writing Object keys in lower camel case

### ISSUE THREAD

**Issue by MeghanDunn** [learn-co-curriculum/javascript-objects#20]
On the browser/tutorial, the instructions say: "2. Assign an object to the variable playlist — the keys will be artist names and the values will be song titles. (What limitation does this impose on our playlist?)" 

The code it was expecting was: var playlist = {artistName: 'song title'} with "artistName" being in lower camel case. 

However, there was no indication in the tutorial itself, the directions, or test code that this naming convention/lower camel case was common practice/procedure or necessary (i.e. a two-word keys must be written in lower camel case) for the function to run. The tutorial only used one-word keys in its examples, so it was difficult to make that leap in logic without ever seeing it done before. 

Having some mention and/or explanation of why this is done this way would likely save students' time and some sanity. :)

**Comment by maxwellbenton** [comment]
Hi @MeghanDunn,

Thank you for providing this feedback. We've updated this lesson and added a note calling out the camel  case convention and noting that tests will likely expect it, which should resolve this issue.

Thank you for contributing to this lesson!
