### ISSUE TITLE
Javascript Objects - misspelled word

### ISSUE THREAD

**Issue by ElijahRus** [learn-co-curriculum/javascript-objects#27]
Hi.
I think the last word is misspelled?
![screenshot 6](https://user-images.githubusercontent.com/29931458/28334369-e9f864a0-6bc8-11e7-863e-48be07d27e2b.png)
![screenshot 6](https://user-images.githubusercontent.com/29931458/28334379-ecc67668-6bc8-11e7-899f-649c15d2935e.png)

 We can make our update function even terser

**Comment by gj** [comment]
Hi @ElijahRus !

Which word is misspelled?

**Comment by gj** [comment]
If you're talking about `terser`, that's spelled correctly. 🙂
