### ISSUE TITLE
I think there is a module missing... not entirely sure 

### ISSUE THREAD

**Issue by ctrlaltpat** [learn-co-curriculum/javascript-objects#40]
1) objects "before all" hook:
     Error: Cannot find module 'jsdom/lib/old-api'
      at require (internal/module.js:11:18)
      at Context.<anonymous> (node_modules/mocha-jsdom/index.js:53:5)

**Comment by jonmackeyparty** [comment]
Had the same issue--the solution given to me was to change the value of "mocha-jsdom" in package.json to "~1.1.0" then run "npm install".  It worked.

**Comment by maxwellbenton** [comment]
Hi @ctrlaltpat,

Thank you for providing this feedback. We've updated the dependencies in this lesson and confirmed that this issue should now be resolved.

 We apologize for any frustration this may have caused, but we appreciate you taking the time to provide this feedback.

Thank you!
