### ISSUE TITLE
Iterate Over Key-Value Pairs

### ISSUE THREAD

**Issue by gasganno** [learn-co-curriculum/javascript-objects#41]
The last bullet point in the objectives is "Iterate over key-value pairs in an object," but the lesson doesn't cover that at all. ?

**Comment by drakeltheryuujin** [comment]
Hi @gasganno 

Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

If you do not believe that this issue has been addressed, please re-open this
issue. 💙
