### ISSUE TITLE
I don't know what's going wrong or why

### ISSUE THREAD

**Issue by parryd4** [learn-co-curriculum/javascript-objects#5]
The last time I ran "learn test" in the console, the Learn IDE didn't run it. After restarting my computer and logging back in to the course, The sidebar displayed "(green) Forked this Lab, and (green) Passed Local Tests" and I thought that was great because this lab was giving me trouble. I went back to the IDE and "learn test" again to see that I failed all 3 tests.

My complete objects.js is:
var playlist = {artist: "Title"};

function updatePlaylist(playlist, artistName, songTitle){
  playlist[artistName] = songTitle;
  return playlist;
}

function removeFromPlaylist(playlist, artistName){
  delete playlist.[artistName];
  return playlist;
}

and I failed all 3 tests:
1) objects defines an object called `playlist`:                                                                                                                                 

```
  AssertionError: expected 'undefined' to equal 'object'
  + expected - actual                                                                                                                                                         

  -undefined                                                                                                                                                                  
  +object                                                                                                                                                                     

  at Context.it (test/objects-test.js:14:32)                                                                                                                                  
```

  2) objects updatePlaylist(playlist, artistName, songTitle) adds the `artistName: songTitle` key-value pair to `playlist`:  
     ReferenceError: updatePlaylist is not defined  
      at Context.it (test/objects-test.js:20:14)                                                                                                                                  

  3) objects removeFromPlaylist(playlist, artistName) removes `artistName` from `playlist`:  
     ReferenceError: removeFromPlaylist is not defined  
      at Context.it (test/objects-test.js:27:14)       

However, if I comment out my removeFromPlaylist function, I pass the first 2 tests and only fail the 3rd.

What confuses me is why I fail all three tests when my 3rd function exists. Playlist is not undefined, it is an object. I can confirm this when I declare it in my browser's Console where "typeof playlist" is "object"
Both of my functions are somehow undefined. Again, in browser's Console "typeof updatePlaylist" is "function" and not undefined.

I don't understand why I fail all 3 tests with the code I've written, and I don't understand why I pass the first 2 tests when my removeFromPlaylist function is commented out.

**Comment by AnnJohn** [comment]
hi @parryd4 sorry for the trouble you're having. Since this looks like a problem specific to your code, could you use Ask a Question and someone from our instructional team will help you out. thanks!
