### ISSUE TITLE
It says forked lab but I don't have files in my Atom

### ISSUE THREAD

**Issue by wongjenn** [learn-co-curriculum/javascript-objects#7]
To Whom It May Concern:

I opened the lab for javascript objects but it never was installed into my Atom. In the lesson, it states the lab was forked. I am not sure what to do now...
Please advise.

Thanks,
Jennifer

**Comment by AnnJohn** [comment]
hi @wongjenn if this is still an issue, could you use Ask a Question and someone from our support team will help you troubleshoot this problem. thanks!
