### ISSUE TITLE
Lesson is Structured as a Reading but Should be a Lab

### ISSUE THREAD

**Issue by cernanb** [learn-co-curriculum/javascript-objects#8]
This lesson is set up as a Readme but the content and the repo indicate this should be set up as a lab. 
<img width="879" alt="screen shot 2016-09-16 at 4 33 18 pm" src="https://cloud.githubusercontent.com/assets/7960757/18603948/4fcd3910-7c2b-11e6-91c6-af228b7799fa.png">

**Comment by AnnJohn** [comment]
changed, thanks!
